CRITERIAS = {
	"Item_teir_to_keep": [
		"Ancestral"
	],
    "Rogue": {
        "Helm": {
			"needed_to_match": 3,
            "Basic Skill Attack Speed": 0,
            "Cooldown Reduction": 0,
            "Life On Kill": 0,
            "Maximum Life": 0,
            "Total Armor": 0,
            "Ranks of Cold Imbuement": 0,
            "Ranks of Poison Imbuement": 0,
            "Ranks of Shadow Imbuement": 0,
        },
        "Chest": {
			"needed_to_match": 3,
			"Damage Reduction": 0,
			"Damage Reduction from Close Enemies": 0,
			"Damage Reduction from Distant Enemies": 0,
			"Life on Kill": 0,
			"Maximum Life": 0,
			"Total Armor": 0,
			"Damage Reduction from Enemies That Are Poisoned": 0,
        },
        "Gloves": {
			"needed_to_match": 3,
            "Attack Speed": 0,
            "Critical Strike Chance": 0,
            "Lucky Hit Chance": 0,
            "Ranks of Barrage": 0,
            "Ranks of Flurry": 0,
            "Ranks of Penetrating Shot": 0,
            "Ranks of Rapid Fire": 0,
            "Ranks of Twisting Blades": 0,
        },
		"Pants": {
			"needed_to_match": 3,
			"Damage Reduction": 0,
			"Damage Reduction while Injured": 0,
			"Damage Reduction from Close Enemies": 0,
			"Damage Reduction from Distant Enemies": 0,
			"Maximum Life": 0,
			"Total Armor": 0,
			"Damage Reduction from Enemies that are Poisoned": 0,
		},
		"Boots": {
			"needed_to_match": 3,
			"Dexterity": 0,
			"Damage Reduction while Injured": 0,
			"Movement Speed": 0,
			"Energy Cost Reduction": 0,
		},
        "Amulet": {
			"needed_to_match": 3,
            "Cooldown Reduction": 0,
			"Damage Reduction": 0,
			"Damage Reduction while Injured": 0,
			"Movement Speed": 0,
			"Total Armor": 0,
			"Damage Reduction from Enemies That Are Poisoned": 0,
			"Energy Cost Reduction": 0,
			"Rank of All Imbuement Skills": 0,
			"Ranks of the Exploit Passive": 0,
			"Ranks of the Frigid Finesse Passive": 0,
			"Ranks of the Malice Passive": 0,
			"Ranks of the Weapon Mastery Passive": 0,
        },
		"Ring": {
			"needed_to_match": 3,
			"Critical Strike Chance": 0,
			"Critical Strike Damage": 0,
			"Lucky Hit Chance": 0,
			"Maximum Life": 0,
			"Vulnerable Damage": 0,
			"Critical Strike Damage with Imbued Skills": 0,
		},
		"Damage Per Second": {
			"needed_to_match": 3,
			"Dexterity": 0,
			"All Stats": 0,
			"Core Skill Damage": 0,
			"Critical Strike Damage": 0,
			"Critical Strike Damage with Imbued Skills": 0,
			"Vulnerable Damage": 0,
		},
		"Shield": {
			"needed_to_match": 3,
			"None": 0
		}
    }
}