CRITERIAS = {
    "Item_teir_to_keep": [
        # "Normal",
        # "Sacred",
        "Ancestral",
    ],
    "Rogue": {
        "Helm": {
            "match_needed": 3,
            "attributes_needed": {
                "Basic Skill Attack Speed": 0,
                "Cooldown Reduction": 0,
                "Life On Kill": 0,
                "Maximum Life": 0,
                "Total Armor": 0,
                "Ranks of Cold Imbuement": 0,
                "Ranks of Shadow Imbuement": 0,
                "Ranks of Poison Imbuement": 0,
            },
        },
        "Chest": {
            "match_needed": 3,
            "attributes_needed": {
                "Damage Reduction": 0,
                "Damage Reduction from Close Enemies": 0,
                "Damage Reduction from Distant Enemies": 0,
                "Life on Kill": 0,
                "Maximum Life": 0,
                "Total Armor": 0,
                "Damage Reduction from Enemies That Are Poisoned": 0,
            },
        },
        "Gloves": {
            "match_needed": 3,
            "attributes_needed": {
                "Attack Speed": 0,
                "Critical Strike Chance": 0,
                "Lucky Hit Chance": 0,
                "Ranks of Barrage": 0,
                "Ranks of Flurry": 0,
                "Ranks of Penetrating Shot": 0,
                "Ranks of Rapid Fire": 0,
                "Ranks of Twisting Blades": 0,
            },
        },
        "Pants": {
            "match_needed": 3,
            "attributes_needed": {
                "Damage Reduction": 0,
                "Damage Reduction while Injured": 0,
                "Damage Reduction from Close Enemies": 0,
                "Damage Reduction from Distant Enemies": 0,
                "Maximum Life": 0,
                "Total Armor": 0,
                "Damage Reduction from Enemies that are Poisoned": 0,
            },
        },
        "Boots": {
            "match_needed": 3,
            "attributes_needed": {
                "Dexterity": 0,
                "Damage Reduction while Injured": 0,
                "Movement Speed": 0,
                "Energy Cost Reduction": 0,
            },
        },
        "Amulet": {
            "match_needed": 3,
            "attributes_needed": {
                "Cooldown Reduction": 0,
                "Damage Reduction": 0,
                "Damage Reduction while Injured": 0,
                "Movement Speed": 0,
                "Total Armor": 0,
                "Damage Reduction from Enemies That Are Poisoned": 0,
                "Energy Cost Reduction": 0,
                "Rank of All Imbuement Skills": 0,
                "Ranks of the Exploit Passive": 0,
                "Ranks of the Frigid Finesse Passive": 0,
                "Ranks of the Malice Passive": 0,
                "Ranks of the Weapon Mastery Passive": 0,
            },
        },
        "Ring": {
            "match_needed": 3,
            "attributes_needed": {
                "Critical Strike Chance": 0,
                "Critical Strike Damage": 0,
                "Lucky Hit Chance": 0,
                "Maximum Life": 0,
                "Vulnerable Damage": 0,
                "Critical Strike Damage with Imbued Skills": 0,
            },
        },
        "Weapon": {
            "match_needed": 3,
            "attributes_needed": {
                "Dexterity": 0,
                "All Stats": 0,
                # "Core Skill Damage": 0,
                "Critical Strike Damage": 16,
                "Critical Strike Damage with Imbued Skills": 0,
                "Vulnerable Damage": 0,
            },
        },
        "Shield": {
            "match_needed": 3,
            "attributes_needed": {
            },
        }
    }
}

ALL_GEAR_TYPES = [
    "Helm",
    "Chest",
    "Gloves",
    "Pants",
    "Boots",
    "Amulet",
    "Ring",
    "Axe",
    "Dagger",
    "Mace",
    "Sword",
    "Scythe",
    "Wand",
    "Staff",
    "Polearm",
    "Two-Handed Axe",
    "Two-Handed Mace",
    "Two-Handed Sword",
    "Two-Handed Scythe",
    "Bow",
    "Crossbow",
    "Totem",
    "Focus",
    "Shield",
]

WEAPONS_LIST = {
    "Axe": "Damage to Healthy Enemies",
    "Dagger": "Damage to Close Enemies",
    "Mace": "Overpower Damage",
    "Sword": "Critical Strike Damage",
    "Scythe": "Life on Kill",
    "Wand": "Lucky Hit Chance",
    "Staff": "Damage to Crowd Controlled Enemies",
    "Polearm": "Damage to Injured Enemies", 
    "Two-Handed Axe": "Damage to Healthy Enemies",
    "Two-Handed Mace": "Overpower Damage",
    "Two-Handed Sword": "Critical Strike Damage",
    "Two-Handed Scythe": "Life on Kill",
    "Bow": "Damage to Distant Enemies",
    "Crossbow": "Vulnerable Damage",
    "Totem": "Cooldown Reduction",
    "Focus": "Cooldown Reduction",
    "Shield": "Block Chance",
}