ITEM_ATTR_LIST = {
    "Helm": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Barrier Generation": {"increment": 0.1, "max_value": 0 },
            "Basic Skill Attack Speed": {"increment": 0.1, "max_value": 0 },
            "Cold Resistance": {"increment": 0.1, "max_value": 0 },
            "Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Crowd Control Duration": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Fire Resistance": {"increment": 0.1, "max_value": 0 },
            "Healing Received": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Life On Kill": {"increment": 1, "max_value": 0 },
            "Life Regeneration while Not Damaged Recently": {"increment": 1, "max_value": 0 },
            "Lightning Resistance": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit Chance while You Have a Barrier": {"increment": 0.1, "max_value": 0 },
            "Maximum Life": {"increment": 1, "max_value": 0 },
            "Poison Resistance": {"increment": 0.1, "max_value": 0 },
            "Shadow Resistance": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Total Armor": {"increment": 1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {
            "Maximum Fury": {"increment": 1, "max_value": 0 },
            "Ranks of Death Blow": {"increment": 1, "max_value": 3 },
            "Ranks of Rupture": {"increment": 1, "max_value": 3 },
            "Ranks of Steel Grasp": {"increment": 1, "max_value": 3 },
        },
        "Druid": {
            "Maximum Spirit": {"increment": 1, "max_value": 0 },
            "Ranks of Poison Creeper": {"increment": 1, "max_value": 3 },
            "Ranks of Ravens": {"increment": 1, "max_value": 3 },
            "Ranks of Wolves": {"increment": 1, "max_value": 3 },
        },
        "Necromancer": {
            "Maximum Essence": {"increment": 1, "max_value": 0 },
            "Ranks of Decrepify": {"increment": 1, "max_value": 3 },
            "Ranks of Iron Maiden": {"increment": 1, "max_value": 3 },
        },
        "Rogue": {
            "Damage with Dual-Wielded Weapons": {"increment": 0.1, "max_value": 0 },
            "Maximum Energy": {"increment": 1, "max_value": 0 },
            "Ranks of Cold Imbuement": {"increment": 1, "max_value": 3 },
            "Ranks of Poison Imbuement": {"increment": 1, "max_value": 3 },
            "Ranks of Shadow Imbuement": {"increment": 1, "max_value": 3 },
        },
        "Sorcerer": {
            "Maximum Mana": {"increment": 1, "max_value": 0 },
            "Ranks of Hydra": {"increment": 1, "max_value": 3 },
            "Ranks of Ice Blades": {"increment": 1, "max_value": 3 },
            "Ranks of Lightning Spear": {"increment": 1, "max_value": 3 },
        },
    },
    "Chest": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Barrier Generation": {"increment": 0.1, "max_value": 0 },
            "Cold Resistance": {"increment": 0.1, "max_value": 0 },
            "Control Impaired Duration": {"increment": 0.1, "max_value": 0 },
            "Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Fire Resistance": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Life on Kill": {"increment": 1, "max_value": 0 },
            "Lightning Resistance": {"increment": 0.1, "max_value": 0 },
            "Maximum Life": {"increment": 1, "max_value": 0 },
            "Poison Resistance": {"increment": 0.1, "max_value": 0 },
            "Shadow Resistance": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Thorns": {"increment": 1, "max_value": 0 },
            "Total Armor": {"increment": 0.1, "max_value": 0 },
            "Ultimate Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {
            "Brawling Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Bleeding": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Ranks of Challenging Shout": {"increment": 1, "max_value": 3 },
            "Ranks of Ground Stomp": {"increment": 1, "max_value": 3 },
            "Ranks of Iron Skin": {"increment": 1, "max_value": 3 },
            "Ranks of Rallying Cry": {"increment": 1, "max_value": 3 },
            "Weapon Mastery Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Druid": {
            "Companion Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Poisoned": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Damage whiile in Human Form": {"increment": 0.1, "max_value": 0 },
            "Damage while Shapeshifted": {"increment": 0.1, "max_value": 0 },
            "Earth Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Lightning Damage": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage with Werebear Skills": {"increment": 0.1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Poison Damage": {"increment": 0.1, "max_value": 0 },
            "Ranks of Blood Howl": {"increment": 1, "max_value": 3 },
            "Ranks of Cyclone Armor": {"increment": 1, "max_value": 3 },
            "Ranks of Debilitating Roar": {"increment": 1, "max_value": 3 },
            "Ranks of Earthen Bulwark": {"increment": 1, "max_value": 3 },
            "Storm Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Werebear Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Werewolf Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Blood Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Bone Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage for 4 Seconds After Picking Up a Blood Orb": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Affected By Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Darkness Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Maximum Minion Life": {"increment": 0.1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Shadow Damage": {"increment": 0.1, "max_value": 0 },
            "Summoning Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Rogue": {
            "Cutthroat Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Poisoned": {"increment": 0.1, "max_value": 0 },
            "Damage with Dual-Wielded Weapons": {"increment": 0.1, "max_value": 0 },
            "Damage with Ranged Weapons": {"increment": 0.1, "max_value": 0 },
            "Damage with Skills that Swap to New Weapons": {"increment": 0.1, "max_value": 0 },
            "Imbued Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Marksman Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Poison Damage": {"increment": 0.1, "max_value": 0 },
            "Shadow Damage": {"increment": 0.1, "max_value": 0 },
            "Trap Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Sorcerer": {
            "Barrier Generation": {"increment": 0.1, "max_value": 0 },
            "Cold Damage": {"increment": 0.1, "max_value": 0 },
            "Conjuration Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Burning": {"increment": 0.1, "max_value": 0 },
            "Fire Damage": {"increment": 0.1, "max_value": 0 },
            "Frost Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Lightning Damage": {"increment": 0.1, "max_value": 0 },
            "Pyromancy Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Shock Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
    },
    "Gloves": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Attack Speed": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance Against Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Lucky Hit Chance": {"increment": 0.1, "max_value": 0 },
            "Chance to Restore [X]% Primary Resource": {"increment": 0.1, "max_value": 0 },
            "Up to a [X]% Chance to Heal": {"increment": 0.1, "max_value": 0 },
            "Up to a [X]% Chance to Slow": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 0.1, "max_value": 0 },
            "Willpower": {"increment": 0.1, "max_value": 0 },
        },
        "Barbarian": {
            "Physical Damage Over Time": {"increment": 0.1, "max_value": 0 },
            "Ranks of Double Swing": {"increment": 1, "max_value": 3 },
            "Ranks of Hammer of the Ancients": {"increment": 1, "max_value": 3 },
            "Ranks of Rend": {"increment": 1, "max_value": 3 },
            "Ranks of Upheaval": {"increment": 1, "max_value": 3 },
            "Ranks of Whirlwind": {"increment": 1, "max_value": 3 },
        },
        "Druid": {
            "Critical Strike Damage with Earth Skills": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Werewolf Skills": {"increment": 0.1, "max_value": 0 },
            "Ranks of Landslide": {"increment": 1, "max_value": 3 },
            "Ranks of Lightning Storm": {"increment": 1, "max_value": 3 },
            "Ranks of Pulverize": {"increment": 1, "max_value": 3 },
            "Ranks of Shred": {"increment": 1, "max_value": 3 },
            "Ranks of Tornado": {"increment": 1, "max_value": 3 },
            "Storm Skill Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Critical Strike Damage with Bone Skills": {"increment": 0.1, "max_value": 0 },
            "Ranks of Blight": {"increment": 1, "max_value": 3 },
            "Ranks of Blood Lance": {"increment": 1, "max_value": 3 },
            "Ranks of Blood Surge": {"increment": 1, "max_value": 3 },
            "Ranks of Bone Spear": {"increment": 1, "max_value": 3 },
            "Ranks of Sever": {"increment": 1, "max_value": 3 },
            "Shadow Damage Over Time": {"increment": 0.1, "max_value": 0 },
        },
        "Rogue": {
            "Attack Speed for 4 seconds after Dodging an Attack": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Imbued Skills": {"increment": 0.1, "max_value": 0 },
            "Ranks of Barrage": {"increment": 1, "max_value": 3 },
            "Ranks of Flurry": {"increment": 1, "max_value": 3 },
            "Ranks of Penetrating Shot": {"increment": 1, "max_value": 3 },
            "Ranks of Rapid Fire": {"increment": 1, "max_value": 3 },
            "Ranks of Twisting Blades": {"increment": 1, "max_value": 3 },
            "Reduces the Arm Time of your Trap Skills": {"increment": 0.1, "max_value": 0 },
            "Trap Skill Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
        },
        "Sorcerer": {
            "Fire Damage Over Time": {"increment": 0.1, "max_value": 0 },
            "Lightning Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Ranks of Chain LightningRanks of Charged Bolts": {"increment": 1, "max_value": 3 },
            "Ranks of Fireball": {"increment": 1, "max_value": 3 },
            "Ranks of Frozen Orb": {"increment": 1, "max_value": 3 },
            "Ranks of Ice Shards": {"increment": 1, "max_value": 3 },
            "Ranks of Incinerate": {"increment": 1, "max_value": 3 },
        },
    },
    "Pants": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Control Impaired Duration Reduction": {"increment": 0.1, "max_value": 0 },
            "Damage for 4 seconds After Killing an Elite": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Dodge Chance": {"increment": 0.1, "max_value": 0 },
            "Dodge Chance Against Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Healing Received": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Life Regeneration while Not Damaged Recently": {"increment": 1, "max_value": 0 },
            "Maximum Life": {"increment": 1, "max_value": 0 },
            "Potion Capacity": {"increment": 1, "max_value": 0 },
            "Potion Drop Rate": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Thorns": {"increment": 1, "max_value": 0 },
            "Total Armor": {"increment": 0.1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {
            "Berserking Duration": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Bleeding": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Ranks of Charge": {"increment": 1, "max_value": 3 },
            "Ranks of Kick": {"increment": 1, "max_value": 3 },
            "Ranks of Leap": {"increment": 1, "max_value": 3 },
            "Ranks of War Cry": {"increment": 1, "max_value": 3 },
        },
        "Druid": {
            "Damage Reduction from Enemies that are Poisoned": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Ranks of Boulder": {"increment": 1, "max_value": 3 },
            "Ranks of Hurricane": {"increment": 1, "max_value": 3 },
            "Ranks of Rabies": {"increment": 1, "max_value": 3 },
            "Ranks of Trample": {"increment": 1, "max_value": 3 },
            "Total Armor while in Werebear Form": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Damage Reduction from Affected By Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Ranks of Blood Mist": {"increment": 1, "max_value": 3 },
            "Ranks of Bone Prison": {"increment": 1, "max_value": 3 },
            "Ranks of Corpse Explosion": {"increment": 1, "max_value": 3 },
        },
        "Rogue": {
            "Damage for 4 Seconds After Dodging an Attack": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies that are Poisoned": {"increment": 0.1, "max_value": 0 },
            "Imbuement Skill Cooldown": {"increment": 0.1, "max_value": 0 },
            "Ranks of Concealment": {"increment": 1, "max_value": 3 },
            "Ranks of Dark Shroud": {"increment": 1, "max_value": 3 },
            "Ranks of Poison Trap": {"increment": 1, "max_value": 3 },
            "Ranks of Smoke Grenade": {"increment": 1, "max_value": 3 },
        },
        "Sorcerer": {
            "Crackling Energy Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Burning": {"increment": 0.1, "max_value": 0 },
            "Ranks of Ball Lightning": {"increment": 1, "max_value": 3 },
            "Ranks of Blizzard": {"increment": 1, "max_value": 3 },
            "Ranks of Firewall": {"increment": 1, "max_value": 3 },
            "Ranks of Meteor": {"increment": 1, "max_value": 3 },
        },
    },
    "Boots": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Cold Resistance": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Injured": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Dodge Chance": {"increment": 0.1, "max_value": 0 },
            "Dodge Chance Against Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Fire Resistance": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 0.1, "max_value": 0 },
            "Lightning Resistance": {"increment": 0.1, "max_value": 0 },
            "Movement Speed": {"increment": 0.1, "max_value": 0 },
            "Movement Speed for 4 seconds After Killing an Elite": {"increment": 0.1, "max_value": 0 },
            "Poison Resistance": {"increment": 0.1, "max_value": 0 },
            "Shadow Resistance": {"increment": 0.1, "max_value": 0 },
            "Shrine Buff Duration": {"increment": 0.1, "max_value": 0 },
            "Slow Duration Reduction": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {
            "Berserking Duration": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Fury Cost Reduction": {"increment": 0.1, "max_value": 0 },
        },
        "Druid": {
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Spirit Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Total Armor while in Werewolf Form": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Essence Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Ranks of Bone Spirit": {"increment": 1, "max_value": 3 },
            "Ranks of Corpse Tendrils": {"increment": 1, "max_value": 3 },
        },
        "Rogue": {
            "Energy Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Ranks of Caltrops": {"increment": 1, "max_value": 3 },
            "Ranks of Dash": {"increment": 1, "max_value": 3 },
            "Ranks of Shadow Step": {"increment": 1, "max_value": 3 },
        },
        "Sorcerer": {
            "Crackling Energy Damage": {"increment": 0.1, "max_value": 0 },
            "Mana Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Ranks of Flame Shield": {"increment": 1, "max_value": 3 },
            "Ranks of Frost Nova": {"increment": 1, "max_value": 3 },
            "Ranks of Ice Armor": {"increment": 1, "max_value": 3 },
            "Ranks of Teleport": {"increment": 1, "max_value": 3 },
        },
    },
    "Amulet": {
        "All Classes": {
            "Control Impaired Duration Reduction": {"increment": 0.1, "max_value": 0 },
            "Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance Against Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Crowd Control Duration": {"increment": 0.1, "max_value": 0 },
            "Damage": {"increment": 0.1, "max_value": 0 },
            "Damage for 4 seconds After Killing an Elite": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Distance Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Injured": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Dodge Chance": {"increment": 0.1, "max_value": 0 },
            "Healing Received": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Lucky Hit Chance while You Have a Barrier": {"increment": 0.1, "max_value": 0 },
            "Movement Speed": {"increment": 0.1, "max_value": 0 },
            "Movement Speed for 4 Seconds After Killing an Elite": {"increment": 0.1, "max_value": 0 },
            "Shrine Buff Duration": {"increment": 0.1, "max_value": 0 },
            "Slow Duration Reduction": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Thorns": {"increment": 1, "max_value": 0 },
            "Total Armor": {"increment": 0.1, "max_value": 0 },
            "Ultimate Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {
            "Brawling Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Bleeding": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Damage with Dual-Wielded Weapons": {"increment": 0.1, "max_value": 0 },
            "Damage with Skills that Swap to New Weapons": {"increment": 0.1, "max_value": 0 },
            "Damage with Two-Handed Bludgeoning Weapons": {"increment": 0.1, "max_value": 0 },
            "Damage with Two-Handed Slashing Weapons": {"increment": 0.1, "max_value": 0 },
            "Fury Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage with Two-Handed Bludgeoning Weapons": {"increment": 0.1, "max_value": 0 },
            "Ranks of All Defensive Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Weapon Mastery Skills": {"increment": 1, "max_value": 3 },
            "Ranks of the Brute Force Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Counteroffensive Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Cut to the Bone Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Heavy Handed Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the No Mercy Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Outburst Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Slaying Strike Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Tough as Nails Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Wallop Passive": {"increment": 1, "max_value": 3 },
            "Weapon Mastery Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Druid": {
            "Companion Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Damage while in Human Form": {"increment": 0.1, "max_value": 0 },
            "Damage while Shapeshifted": {"increment": 0.1, "max_value": 0 },
            "Earth Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage with Werebear Skills": {"increment": 0.1, "max_value": 0 },
            "Ranks of All Companion Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Defensive Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Wrath Skills": {"increment": 1, "max_value": 3 },
            "Ranks of the Call of the Wild Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Crushing Earth Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Defiance Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Envenom Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Natural Disaster Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Nature's Reach Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Quickshift Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Resonance Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Stone Guard Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Toxic Claws Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Wild Impulses Passive": {"increment": 1, "max_value": 3 },
            "Spirit Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Storm Skill Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Storm Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Total Armor while in Werewolf Form": {"increment": 0.1, "max_value": 0 },
            "Werebear Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Werewolf Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Blood Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Bone Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Affected By Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Darkness Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Essence Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Minion Attack Speed": {"increment": 0.1, "max_value": 0 },
            "Ranks of All Corpse Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Curse Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Macabre Skills": {"increment": 1, "max_value": 3 },
            "Ranks of the Amplify Damage Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Coalesced Blood Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Compound Fracture Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Death's Reach Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Evulsion Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Fueled by Death Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Gloom Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Hellbent Commander Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Imperfectly Balanced Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Terror Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Tides of Blood Passive": {"increment": 1, "max_value": 3 },
            "Summoning Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Rogue": {
            "Attack Speed for 4 seconds after Dodging an Attack": {"increment": 0.1, "max_value": 0 },
            "Cutthroat Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Poisoned": {"increment": 0.1, "max_value": 0 },
            "Damage with Dual-Wielded Weapons": {"increment": 0.1, "max_value": 0 },
            "Damage with Ranged Weapons": {"increment": 0.1, "max_value": 0 },
            "Energy Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Imbued Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Imbuement Skill Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Marksman Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Rank of All Agility Skills": {"increment": 1, "max_value": 3 },
            "Rank of All Imbuement Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Subterfuge Skills": {"increment": 1, "max_value": 3 },
            "Ranks of the Deadly Venom Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Exploit Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Frigid Finesse Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Impetus Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Malice Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Weapon Mastery Passive": {"increment": 1, "max_value": 3 },
            "Reduces the Arm Time of your Trap Skills": {"increment": 0.1, "max_value": 0 },
            "Trap Skill Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Trap Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Sorcerer": {
            "Conjuration Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Frost Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Mana Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Pyromancy Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Ranks of All Conjuration Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Defensive Skills": {"increment": 1, "max_value": 3 },
            "Ranks of All Mastery Skills": {"increment": 1, "max_value": 3 },
            "Ranks of the Conjuration Mastery Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Devouring Blaze Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Elemental Dominance Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Endless Pyre Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Glass Cannon Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Hoarfrost Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Icy Touch Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Inner Flames Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Permafrost Passive": {"increment": 1, "max_value": 3 },
            "Ranks of the Shocking Impact Passive": {"increment": 1, "max_value": 3 },
            "Shock Skill Damage": {"increment": 0.1, "max_value": 0 },
        },
    },
    "Ring": {
        "All Classes": {
            "Barrier Generation": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Over Time": {"increment": 0.1, "max_value": 0 },
            "Damage to Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Crowd Controlled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Slowed Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Stunned Enemies": {"increment": 0.1, "max_value": 0 },
            "Life Regeneration while Not Damaged Recently": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit Chance": {"increment": 0.1, "max_value": 0 },
            "Maximum Life": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage": {"increment": 0.1, "max_value": 0 },
            "Resource Generation": {"increment": 0.1, "max_value": 0 },
            "Vulnerable Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Barbarian": {
            "Damage to Bleeding Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage while Berserking": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Maximum Fury": {"increment": 1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Druid": {
            "Critical Strike Damage with Earth Skills": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Werewolf Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Poisoned Enemies": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Lightning Damage": {"increment": 0.1, "max_value": 0 },
            "Maximum Spirit": {"increment": 1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Poison Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Blood Orb Healing": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Bone Skills": {"increment": 0.1, "max_value": 0 },
            "Damage for 4 Seconds After Picking Up a Blood Orb": {"increment": 0.1, "max_value": 0 },
            "Damage to Affected by Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Golems Inherit [X]% of Your Thorns": {"increment": 0.1, "max_value": 0 },
            "Maximum Essence": {"increment": 1, "max_value": 0 },
            "Maximum Minion Life": {"increment": 0.1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Shadow Damage": {"increment": 0.1, "max_value": 0 },
            "Skeletal Mages Inherit [X]% of Your Thorns": {"increment": 0.1, "max_value": 0 },
            "Skeletal Warriors Inherit [X]% of Your Thorns": {"increment": 0.1, "max_value": 0 },
        },
        "Rogue": {
            "Cold Damage": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Imbued Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Chilled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Dazed Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Enemies Affected by Trap Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Frozen Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Poisoned Enemies": {"increment": 0.1, "max_value": 0 },
            "Imbued Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Maximum Energy": {"increment": 1, "max_value": 0 },
            "Physical Damage": {"increment": 0.1, "max_value": 0 },
            "Shadow Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Sorcerer": {
            "Cold Damage": {"increment": 0.1, "max_value": 0 },
            "Cracking Energy Damage": {"increment": 0.1, "max_value": 0 },
            "Damage to Burning Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Chilled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Frozen Enemies": {"increment": 0.1, "max_value": 0 },
            "Fire Damage": {"increment": 0.1, "max_value": 0 },
            "Lightning Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Lightning Damage": {"increment": 0.1, "max_value": 0 },
            "Maximum Mana": {"increment": 1, "max_value": 0 },
        },
    },
    "One-Handed Weapon": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Basic Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Core Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Over Time": {"increment": 0.1, "max_value": 0 },
            "Damage to Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Crowd Controlled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Slowed Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Stunned Enemies": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Up to [X] Chance to Execute Injured Non-Elites": {"increment": 0.1, "max_value": 0 },
            "Mastery Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage": {"increment": 0.1, "max_value": 0 },
            "Ultimate Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Vulnerable Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Barbarian": {
            "Damage to Bleeding Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage while Berserking": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
        },
        "Druid": {
            "Critical Strike Damage with Earth Skills": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Werewolf Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Poisoned Enemies": {"increment": 0.1, "max_value": 0 },
            "Lightning Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage with Werebear Skills": {"increment": 0.1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Necromancer": {
            "Critical Strike Damage with Bone Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Affected by Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
        },
        "Rogue": {
            "Critical Strike Damage with Imbued Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Chilled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Dazed Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Enemies Affected by Trap Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Frozen Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Poisoned Enemies": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
        },
        "Sorcerer": {
            "Damage to Burning Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Chilled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Frozen Enemies": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Lightning Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
        },
    },
    "Two-Handed Weapon": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Basic Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Core Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Over Time": {"increment": 0.1, "max_value": 0 },
            "Damage to Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Crowd Controlled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Slowed Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Stunned Enemies": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Up to [X] Chance to Execute Injured Non-Elites": {"increment": 0.1, "max_value": 0 },
            "Mastery Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage": {"increment": 0.1, "max_value": 0 },
            "Ultimate Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Vulnerable Damage": {"increment": 0.1, "max_value": 0 },
        },
        "Barbarian": {
            "Damage to Bleeding Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage while Berserking": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
        },
        "Druid": {
            "Critical Strike Damage with Earth Skills": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Damage with Werewolf Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Poisoned Enemies": {"increment": 0.1, "max_value": 0 },
            "Lightning Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
            "Overpower Damage with Werebear Skills": {"increment": 0.1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Necromancer": {
            "Critical Strike Damage with Bone Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Affected by Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
        },
        "Rogue": {
            "Critical Strike Damage with Imbued Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Chilled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Dazed Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Enemies Affected by Trap Skills": {"increment": 0.1, "max_value": 0 },
            "Damage to Frozen Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Poisoned Enemies": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
        },
        "Sorcerer": {
            "Damage to Burning Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Chilled Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage to Frozen Enemies": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Lightning Critical Strike Damage": {"increment": 0.1, "max_value": 0 },
        },
    },
    "Off Hand": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Barrier Generation": {"increment": 0.1, "max_value": 0 },
            "Basic Skill Attack Speed": {"increment": 0.1, "max_value": 0 },
            "Basic Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance Against Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Crowd Control Duration": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Healing Received": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Life On Kill": {"increment": 1, "max_value": 0 },
            "Lucky Hit Chance": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit Chance while You Have a Barrier": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Chance to Restore [X]% Primary Resource": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Up to [X]% Chance to Slow": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Up to a [X]% Chance to Heal": {"increment": 0.1, "max_value": 0 },
            "Resource Generation": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {

        },
        "Druid": {
            "Damage Reduction from Enemies That Are Poisoned": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Spirit Cost Reduction": {"increment": 0.1, "max_value": 0 },
        },
        "Necromancer": {
            "Blood Orb Healing": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Affected By Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Essence Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Maximum Minion Life": {"increment": 0.1, "max_value": 0 },
        },
        "Rogue": {

        },
        "Sorcerer": {
            "Crackling Energy Damage": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Enemies That Are Burning": {"increment": 0.1, "max_value": 0 },
            "Mana Cost Reduction": {"increment": 0.1, "max_value": 0 },
        },
    },
    "Shield": {
        "All Classes": {
            "All Stats": {"increment": 1, "max_value": 0 },
            "Basic Skill Attack Speed": {"increment": 0.1, "max_value": 0 },
            "Basic Skill Damage": {"increment": 0.1, "max_value": 0 },
            "Cooldown Reduction": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance": {"increment": 0.1, "max_value": 0 },
            "Critical Strike Chance Against Injured Enemies": {"increment": 0.1, "max_value": 0 },
            "Crowd Control Duration": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Close Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Distant Enemies": {"increment": 0.1, "max_value": 0 },
            "Dexterity": {"increment": 1, "max_value": 0 },
            "Healing Received": {"increment": 0.1, "max_value": 0 },
            "Intelligence": {"increment": 1, "max_value": 0 },
            "Life On Kill": {"increment": 1, "max_value": 0 },
            "Lucky Hit Chance": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Chance to Restore [X]% Primary Resource": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Up to [X]% Chance to Slow": {"increment": 0.1, "max_value": 0 },
            "Lucky Hit: Up to a [X]% Chance to Heal": {"increment": 0.1, "max_value": 0 },
            "Maximum Life": {"increment": 1, "max_value": 0 },
            "Resistance to All Elements": {"increment": 0.1, "max_value": 0 },
            "Resource Generation": {"increment": 0.1, "max_value": 0 },
            "Strength": {"increment": 1, "max_value": 0 },
            "Thorns": {"increment": 1, "max_value": 0 },
            "Willpower": {"increment": 1, "max_value": 0 },
        },
        "Barbarian": {

        },
        "Druid": {

        },
        "Necromancer": {
            "Blood Orb Healing": {"increment": 0.1, "max_value": 0 },
            "Damage for 4 Seconds After Picking Up a Blood Orb": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction from Affected By Shadow Damage Over Time Enemies": {"increment": 0.1, "max_value": 0 },
            "Damage Reduction while Fortified": {"increment": 0.1, "max_value": 0 },
            "Essence Cost Reduction": {"increment": 0.1, "max_value": 0 },
            "Fortify Generation": {"increment": 0.1, "max_value": 0 },
            "Maximum Minion Life": {"increment": 0.1, "max_value": 0 },
            "Minion Attack Speed": {"increment": 0.1, "max_value": 0 },
        },
        "Rogue": {

        },
        "Sorcerer": {
            
        },
    }
}